# -*- coding: utf-8 -*-
"""生成 exercises.manifest.json（35 章 / 151 个练习的目录清单）。"""
import json

EX = "_sources/bevy-src/examples"
LEARN = "_sources/learn/md"

chapters = [
    ("ch01_hello_engine", "你好，Bevy！", 6,
     [f"{EX}/app/empty.rs", f"{EX}/app/empty_defaults.rs", f"{LEARN}/getting-started.md"],
     "创建 App、添加 DefaultPlugins、run()、println 日志"),
    ("ch02_apps", "App 与应用", 6,
     [f"{EX}/app/headless.rs", f"{EX}/app/no_renderer.rs", f"{EX}/app/logs.rs",
      f"{EX}/app/settings.rs", f"{EX}/app/return_after_run.rs", f"{EX}/app/custom_loop.rs",
      f"{EX}/app/thread_pool_resources.rs"],
     "无窗口运行、ScheduleRunnerPlugin、日志级别、AppExit、手动 update 循环、线程池"),
    ("ch03_ecs", "ECS 实体组件系统", 7,
     [f"{EX}/ecs/startup_system.rs", f"{EX}/ecs/ecs_guide.rs", f"{EX}/ecs/hierarchy.rs",
      f"{LEARN}/getting-started_ecs.md"],
     "Entity、Component、Bundle、System、Query、Commands、Startup/Update 调度"),
    ("ch04_plugins", "插件", 4,
     [f"{EX}/app/plugin.rs", f"{EX}/app/plugin_group.rs", f"{LEARN}/getting-started_plugins.md"],
     "Plugin trait、插件组、插件配置、插件与系统/资源"),
    ("ch05_resources", "资源", 4,
     [f"{LEARN}/getting-started_resources.md", f"{EX}/app/thread_pool_resources.rs",
      f"{EX}/ecs/immutable_components.rs"],
     "Res/ResMut、init_resource/insert_resource/remove_resource、共享可变状态"),
    ("ch06_breakout", "打砖块小游戏", 4,
     [f"{EX}/showcase/breakout.rs"],
     "经典 Breakout：挡板、球、碰撞、计分（拆成小块学习）"),
    ("ch07_2d_basics", "2D 基础", 7,
     [f"{EX}/2d/sprite.rs", f"{EX}/2d/2d_shapes.rs", f"{EX}/2d/move_sprite.rs",
      f"{EX}/2d/rotation.rs", f"{EX}/2d/transparency_2d.rs", f"{EX}/2d/mesh2d.rs",
      f"{EX}/2d/sprite_flipping.rs", f"{EX}/2d/sprite_scale.rs", f"{EX}/2d/text2d.rs"],
     "Sprite、2D 形状、Transform 移动/旋转/缩放、透明度、Mesh2d、Text2d"),
    ("ch08_3d_basics", "3D 基础", 7,
     [f"{EX}/3d/3d_shapes.rs", f"{EX}/3d/3d_scene.rs", f"{EX}/3d/lighting.rs",
      f"{EX}/3d/parenting.rs", f"{EX}/3d/transparency_3d.rs", f"{EX}/3d/orthographic.rs",
      f"{EX}/3d/vertex_colors.rs"],
     "Mesh3d、Camera3d、灯光、材质、父子、透明度、正交相机"),
    ("ch09_animation", "动画", 4,
     [f"{EX}/animation/animated_transform.rs", f"{EX}/animation/eased_motion.rs",
      f"{EX}/animation/easing_functions.rs", f"{EX}/animation/color_animation.rs",
      f"{EX}/animation/animation_events.rs"],
     "AnimatedTransform、缓动、AnimationPlayer、动画事件"),
    ("ch10_audio", "音频", 4,
     [f"{EX}/audio/audio.rs", f"{EX}/audio/audio_control.rs", f"{EX}/audio/play_sound_effect.rs",
      f"{EX}/audio/spatial_audio_3d.rs"],
     "AudioPlayer、AudioBundle、音量/播放控制、PlaySoundEffect、空间音频"),
    ("ch11_camera", "摄像机", 4,
     [f"{EX}/camera/camera_orbit.rs", f"{EX}/camera/pan_camera_controller.rs",
      f"{EX}/camera/projection_zoom.rs", f"{EX}/camera/2d_top_down_camera.rs",
      f"{EX}/camera/free_camera_controller.rs"],
     "Camera2d/Camera3d、跟随、环绕、缩放、控制器"),
    ("ch12_diagnostics", "诊断与日志", 3,
     [f"{EX}/diagnostics/log_diagnostics.rs", f"{EX}/diagnostics/custom_diagnostic.rs",
      f"{EX}/app/logs.rs"],
     "FrameTimeDiagnostics、自定义 Diagnostic、LogPlugin 级别"),
    ("ch13_games", "小游戏合集", 5,
     [f"{EX}/showcase/contributors.rs", f"{EX}/showcase/game_menu.rs",
      f"{EX}/showcase/loading_screen.rs", f"{EX}/showcase/alien_cake_addict.rs"],
     "综合小游戏：菜单、加载屏、弹跳球、吃蛋糕"),
    ("ch14_gizmos", "调试绘制", 4,
     [f"{EX}/gizmos/2d_gizmos.rs", f"{EX}/gizmos/3d_gizmos.rs", f"{EX}/gizmos/axes.rs",
      f"{EX}/gizmos/transform_gizmo.rs", f"{EX}/gizmos/2d_text_gizmos.rs"],
     "Gizmos：线/圆/矩形/轴、2D/3D、调试可视化"),
    ("ch15_math", "数学", 4,
     [f"{EX}/math/cubic_splines.rs", f"{EX}/math/random_sampling.rs",
      f"{EX}/math/custom_primitives.rs", f"{EX}/math/bounding_2d.rs", f"{EX}/math/render_primitives.rs"],
     "Vec2/Vec3 运算、样条、随机、边界盒、数学原语"),
    ("ch16_scene", "场景", 4,
     [f"{EX}/scene/bsn.rs", f"{EX}/scene/world_serialization.rs", f"{EX}/3d/3d_scene.rs"],
     "BSN 场景标记、SceneRoot、世界序列化、加载场景"),
    ("ch17_state", "状态管理", 4,
     [f"{EX}/state/states.rs", f"{EX}/state/computed_states.rs", f"{EX}/state/sub_states.rs",
      f"{EX}/state/custom_transitions.rs"],
     "States、init_state、OnEnter/OnExit、计算状态、子状态、自定义转移"),
    ("ch18_time", "时间与计时器", 4,
     [f"{EX}/time/time.rs", f"{EX}/time/timers.rs", f"{EX}/time/virtual_time.rs",
      f"{EX}/ecs/fixed_timestep.rs"],
     "Time、delta_secs、Timer、Stopwatch、虚拟时间、固定时间步"),
    ("ch19_transform", "变换", 4,
     [f"{EX}/transforms/transform.rs", f"{EX}/transforms/translation.rs",
      f"{EX}/transforms/rotation.rs", f"{EX}/transforms/scale.rs", f"{EX}/transforms/align.rs"],
     "Transform/GlobalTransform、translate/rotate/scale、LookAt、align"),
    ("ch20_input", "输入", 6,
     [f"{EX}/input/keyboard_input.rs", f"{EX}/input/mouse_input.rs", f"{EX}/input/touch_input.rs",
      f"{EX}/input/gamepad_input.rs", f"{EX}/input/keyboard_modifiers.rs",
      f"{EX}/input/char_input_events.rs", f"{EX}/input/mouse_input_events.rs",
      f"{EX}/input/gamepad_input_events.rs", f"{EX}/input/keyboard_input_events.rs"],
     "ButtonInput、键盘/鼠标/触摸/手柄、just_pressed、修饰键、输入事件"),
    ("ch21_ui", "UI 用户界面", 7,
     [f"{EX}/ui/widgets/button.rs", f"{EX}/ui/widgets/standard_widgets.rs",
      f"{EX}/ui/widgets/feathers_counter.rs", f"{EX}/ui/text/text.rs",
      f"{EX}/ui/layout/flex_layout.rs", f"{EX}/ui/layout/anchor_layout.rs",
      f"{EX}/ui/layout/size_constraints.rs", f"{EX}/ui/styling/borders.rs",
      f"{EX}/ui/images/image_node.rs", f"{EX}/ui/relative_cursor_position.rs",
      f"{EX}/ui/ui_scaling.rs"],
     "Node、Text、Button、Interaction、Flex 布局、锚点、边框、图片节点"),
    ("ch22_window", "窗口", 4,
     [f"{EX}/window/window_settings.rs", f"{EX}/window/window_resizing.rs",
      f"{EX}/window/multiple_windows.rs", f"{EX}/window/clear_color.rs",
      f"{EX}/window/scale_factor_override.rs", f"{EX}/window/monitor_info.rs"],
     "WindowPlugin、分辨率/标题/模式、多窗口、ClearColor、缩放因子"),
    ("ch23_movement", "移动", 3,
     [f"{EX}/movement/smooth_follow.rs", f"{EX}/movement/physics_in_fixed_timestep.rs",
      f"{EX}/2d/rotate_to_cursor.rs", f"{EX}/2d/2d_viewport_to_world.rs"],
     "平滑跟随、固定时间步物理、转向、屏幕坐标与世界坐标"),
    ("ch24_async_tasks", "异步任务", 3,
     [f"{EX}/async_tasks/async_compute.rs", f"{EX}/async_tasks/async_channel_pattern.rs",
      f"{EX}/async_tasks/external_source_external_thread.rs"],
     "AsyncComputeTaskPool、spawn、轮询 Task、异步加载"),
    ("ch25_shaders", "着色器入门", 3,
     [f"{EX}/shader/shader_material.rs", f"{EX}/shader/animate_shader.rs",
      f"{EX}/shader/shader_material_2d.rs"],
     "自定义材质、WGSL 内联、uniform、2D 着色器"),
    ("ch26_gltf", "glTF 模型", 4,
     [f"{EX}/gltf/load_gltf.rs", f"{EX}/gltf/update_gltf_scene.rs",
      f"{EX}/gltf/query_gltf_primitives.rs", f"{EX}/gltf/edit_material_on_gltf.rs"],
     "加载 .glb/.gltf、SceneRoot、遍历网格、修改材质"),
    ("ch27_picking", "拾取点击", 4,
     [f"{EX}/picking/simple_picking.rs", f"{EX}/picking/mesh_picking.rs",
      f"{EX}/picking/sprite_picking.rs", f"{EX}/picking/debug_picking.rs",
      f"{EX}/picking/dragdrop_picking.rs"],
     "Pointer<Over>/<Click>、拾取事件、拖拽、调试显示"),
    ("ch28_assets", "资产管理", 5,
     [f"{EX}/asset/asset_loading.rs", f"{EX}/asset/hot_asset_reloading.rs",
      f"{EX}/asset/embedded_asset.rs", f"{EX}/asset/generated_assets.rs",
      f"{EX}/asset/asset_settings.rs", f"{EX}/asset/alter_sprite.rs"],
     "AssetServer、load 回调、热重载、嵌入资产、生成资产"),
    ("ch29_events", "事件与观察者", 4,
     [f"{EX}/ecs/message.rs", f"{EX}/ecs/callbacks.rs", f"{EX}/ecs/observers.rs",
      f"{EX}/ecs/component_hooks.rs"],
     "Message/MessageWriter/MessageReader、触发事件、On<Event>、组件生命周期回调"),
    ("ch30_run_conditions", "运行条件", 3,
     [f"{EX}/ecs/run_conditions.rs", f"{EX}/ecs/system_piping.rs", f"{EX}/ecs/state_scoped.rs"],
     "run_if、condition 组合、系统管道、状态作用域"),
    ("ch31_fixed_timestep", "固定时间步", 3,
     [f"{EX}/ecs/fixed_timestep.rs", f"{EX}/movement/physics_in_fixed_timestep.rs"],
     "FixedUpdate 调度、Time<Fixed>、固定步长物理、插值"),
    ("ch32_change_detection", "变更检测", 3,
     [f"{EX}/ecs/change_detection.rs", f"{EX}/ecs/removal_detection.rs",
      f"{EX}/ecs/entity_disabling.rs"],
     "Added/Changed、RemovedComponents、EntityDisabled"),
    ("ch33_hierarchy", "层级与父子关系", 3,
     [f"{EX}/ecs/hierarchy.rs", f"{EX}/ecs/relationships.rs", f"{EX}/3d/parenting.rs"],
     "Parent/Children、add_child、全局变换、关系组件"),
    ("ch34_ecs_advanced", "高级 ECS", 4,
     [f"{EX}/ecs/one_shot_systems.rs", f"{EX}/ecs/generic_system.rs",
      f"{EX}/ecs/parallel_query.rs", f"{EX}/ecs/custom_schedule.rs",
      f"{EX}/ecs/iter_combinations.rs", f"{EX}/ecs/delayed_commands.rs"],
     "OneShotSystem、泛型系统、并行查询、自定义调度、组合迭代"),
    ("ch35_tips", "实用技巧", 3,
     [f"{EX}/usage/cooldown.rs", f"{EX}/app/log_layers.rs", f"{EX}/app/without_winit.rs"],
     "冷却计时、日志分层、无 winit 运行、任务队列"),
]

total = sum(c[2] for c in chapters)
assert len(chapters) == 35 and total >= 150, (len(chapters), total)
manifest = {"chapters": []}
for i, (slug, title, count, sources, focus) in enumerate(chapters, 1):
    exs = [f"ex_{i:02d}{n:02d}" for n in range(1, count + 1)]
    manifest["chapters"].append({
        "num": i, "slug": slug, "title": title, "count": count,
        "sources": sources, "focus": focus, "exercises": exs,
    })
with open("exercises.manifest.json", "w", encoding="utf-8") as f:
    json.dump(manifest, f, ensure_ascii=False, indent=1)
print("chapters:", len(manifest["chapters"]), "total exercises:", total)
