[package]
name = "exercises"
version = "0.1.0"
edition = "2021"
description = "bevylings 练习题库（故意改错的代码）"

[dependencies]
bevy = { version = "0.19", optional = true }

[features]
default = []
ch_01 = []
ch_02 = []
ch_03 = []
ch_04 = []
ch_05 = []
ch_06 = []
ch_07 = []
ch_08 = []
ch_09 = []
ch_10 = []
ch_11 = []
ch_12 = []
ch_13 = []
ch_14 = []
ch_15 = []
ch_16 = []
ch_17 = []
ch_18 = []
ch_19 = []
ch_20 = []
ch_21 = []
ch_22 = []
ch_23 = []
ch_24 = []
ch_25 = []
ch_26 = []
ch_27 = []
ch_28 = []
ch_29 = []
ch_30 = []
ch_31 = []
ch_32 = []
ch_33 = []
ch_34 = []
ch_35 = []
ex_0101 = ["ch_01", "dep:bevy"]
ex_0102 = ["ch_01", "dep:bevy"]
ex_0103 = ["ch_01", "dep:bevy"]
ex_0104 = ["ch_01", "dep:bevy"]
ex_0105 = ["ch_01", "dep:bevy"]
ex_0106 = ["ch_01", "dep:bevy"]
ex_0201 = ["ch_02", "dep:bevy"]
ex_0202 = ["ch_02", "dep:bevy"]
ex_0203 = ["ch_02", "dep:bevy"]
ex_0204 = ["ch_02", "dep:bevy"]
ex_0205 = ["ch_02", "dep:bevy"]
ex_0206 = ["ch_02", "dep:bevy"]
ex_0301 = ["ch_03", "dep:bevy"]
ex_0302 = ["ch_03", "dep:bevy"]
ex_0303 = ["ch_03", "dep:bevy"]
ex_0304 = ["ch_03", "dep:bevy"]
ex_0305 = ["ch_03", "dep:bevy"]
ex_0306 = ["ch_03", "dep:bevy"]
ex_0307 = ["ch_03", "dep:bevy"]
ex_0401 = ["ch_04", "dep:bevy"]
ex_0402 = ["ch_04", "dep:bevy"]
ex_0403 = ["ch_04", "dep:bevy"]
ex_0404 = ["ch_04", "dep:bevy"]
ex_0501 = ["ch_05", "dep:bevy"]
ex_0502 = ["ch_05", "dep:bevy"]
ex_0503 = ["ch_05", "dep:bevy"]
ex_0504 = ["ch_05", "dep:bevy"]
ex_0601 = ["ch_06", "dep:bevy"]
ex_0602 = ["ch_06", "dep:bevy"]
ex_0603 = ["ch_06", "dep:bevy"]
ex_0604 = ["ch_06", "dep:bevy"]
ex_0701 = ["ch_07", "dep:bevy"]
ex_0702 = ["ch_07", "dep:bevy"]
ex_0703 = ["ch_07", "dep:bevy"]
ex_0704 = ["ch_07", "dep:bevy"]
ex_0705 = ["ch_07", "dep:bevy"]
ex_0706 = ["ch_07", "dep:bevy"]
ex_0707 = ["ch_07", "dep:bevy"]
ex_0801 = ["ch_08", "dep:bevy"]
ex_0802 = ["ch_08", "dep:bevy"]
ex_0803 = ["ch_08", "dep:bevy"]
ex_0804 = ["ch_08", "dep:bevy"]
ex_0805 = ["ch_08", "dep:bevy"]
ex_0806 = ["ch_08", "dep:bevy"]
ex_0807 = ["ch_08", "dep:bevy"]
ex_0901 = ["ch_09", "dep:bevy"]
ex_0902 = ["ch_09", "dep:bevy"]
ex_0903 = ["ch_09", "dep:bevy"]
ex_0904 = ["ch_09", "dep:bevy"]
ex_1001 = ["ch_10", "dep:bevy"]
ex_1002 = ["ch_10", "dep:bevy"]
ex_1003 = ["ch_10", "dep:bevy"]
ex_1004 = ["ch_10", "dep:bevy"]
ex_1101 = ["ch_11", "dep:bevy"]
ex_1102 = ["ch_11", "dep:bevy"]
ex_1103 = ["ch_11", "dep:bevy"]
ex_1104 = ["ch_11", "dep:bevy"]
ex_1201 = ["ch_12", "dep:bevy"]
ex_1202 = ["ch_12", "dep:bevy"]
ex_1203 = ["ch_12", "dep:bevy"]
ex_1301 = ["ch_13", "dep:bevy"]
ex_1302 = ["ch_13", "dep:bevy"]
ex_1303 = ["ch_13", "dep:bevy"]
ex_1304 = ["ch_13", "dep:bevy"]
ex_1305 = ["ch_13", "dep:bevy"]
ex_1401 = ["ch_14", "dep:bevy"]
ex_1402 = ["ch_14", "dep:bevy"]
ex_1403 = ["ch_14", "dep:bevy"]
ex_1404 = ["ch_14", "dep:bevy"]
ex_1501 = ["ch_15", "dep:bevy"]
ex_1502 = ["ch_15", "dep:bevy"]
ex_1503 = ["ch_15", "dep:bevy"]
ex_1504 = ["ch_15", "dep:bevy"]
ex_1601 = ["ch_16", "dep:bevy"]
ex_1602 = ["ch_16", "dep:bevy"]
ex_1603 = ["ch_16", "dep:bevy"]
ex_1604 = ["ch_16", "dep:bevy"]
ex_1701 = ["ch_17", "dep:bevy"]
ex_1702 = ["ch_17", "dep:bevy"]
ex_1703 = ["ch_17", "dep:bevy"]
ex_1704 = ["ch_17", "dep:bevy"]
ex_1801 = ["ch_18", "dep:bevy"]
ex_1802 = ["ch_18", "dep:bevy"]
ex_1803 = ["ch_18", "dep:bevy"]
ex_1804 = ["ch_18", "dep:bevy"]
ex_1901 = ["ch_19", "dep:bevy"]
ex_1902 = ["ch_19", "dep:bevy"]
ex_1903 = ["ch_19", "dep:bevy"]
ex_1904 = ["ch_19", "dep:bevy"]
ex_2001 = ["ch_20", "dep:bevy"]
ex_2002 = ["ch_20", "dep:bevy"]
ex_2003 = ["ch_20", "dep:bevy"]
ex_2004 = ["ch_20", "dep:bevy"]
ex_2005 = ["ch_20", "dep:bevy"]
ex_2006 = ["ch_20", "dep:bevy"]
ex_2101 = ["ch_21", "dep:bevy"]
ex_2102 = ["ch_21", "dep:bevy"]
ex_2103 = ["ch_21", "dep:bevy"]
ex_2104 = ["ch_21", "dep:bevy"]
ex_2105 = ["ch_21", "dep:bevy"]
ex_2106 = ["ch_21", "dep:bevy"]
ex_2107 = ["ch_21", "dep:bevy"]
ex_2201 = ["ch_22", "dep:bevy"]
ex_2202 = ["ch_22", "dep:bevy"]
ex_2203 = ["ch_22", "dep:bevy"]
ex_2204 = ["ch_22", "dep:bevy"]
ex_2301 = ["ch_23", "dep:bevy"]
ex_2302 = ["ch_23", "dep:bevy"]
ex_2303 = ["ch_23", "dep:bevy"]
ex_2401 = ["ch_24", "dep:bevy"]
ex_2402 = ["ch_24", "dep:bevy"]
ex_2403 = ["ch_24", "dep:bevy"]
ex_2501 = ["ch_25", "dep:bevy"]
ex_2502 = ["ch_25", "dep:bevy"]
ex_2503 = ["ch_25", "dep:bevy"]
ex_2601 = ["ch_26", "dep:bevy"]
ex_2602 = ["ch_26", "dep:bevy"]
ex_2603 = ["ch_26", "dep:bevy"]
ex_2604 = ["ch_26", "dep:bevy"]
ex_2701 = ["ch_27", "dep:bevy"]
ex_2702 = ["ch_27", "dep:bevy"]
ex_2703 = ["ch_27", "dep:bevy"]
ex_2704 = ["ch_27", "dep:bevy"]
ex_2801 = ["ch_28", "dep:bevy"]
ex_2802 = ["ch_28", "dep:bevy"]
ex_2803 = ["ch_28", "dep:bevy"]
ex_2804 = ["ch_28", "dep:bevy"]
ex_2805 = ["ch_28", "dep:bevy"]
ex_2901 = ["ch_29", "dep:bevy"]
ex_2902 = ["ch_29", "dep:bevy"]
ex_2903 = ["ch_29", "dep:bevy"]
ex_2904 = ["ch_29", "dep:bevy"]
ex_3001 = ["ch_30", "dep:bevy"]
ex_3002 = ["ch_30", "dep:bevy"]
ex_3003 = ["ch_30", "dep:bevy"]
ex_3101 = ["ch_31", "dep:bevy"]
ex_3102 = ["ch_31", "dep:bevy"]
ex_3103 = ["ch_31", "dep:bevy"]
ex_3201 = ["ch_32", "dep:bevy"]
ex_3202 = ["ch_32", "dep:bevy"]
ex_3203 = ["ch_32", "dep:bevy"]
ex_3301 = ["ch_33", "dep:bevy"]
ex_3302 = ["ch_33", "dep:bevy"]
ex_3303 = ["ch_33", "dep:bevy"]
ex_3401 = ["ch_34", "dep:bevy"]
ex_3402 = ["ch_34", "dep:bevy"]
ex_3403 = ["ch_34", "dep:bevy"]
ex_3404 = ["ch_34", "dep:bevy"]
ex_3501 = ["ch_35", "dep:bevy"]
ex_3502 = ["ch_35", "dep:bevy"]
ex_3503 = ["ch_35", "dep:bevy"]
