[package]
name = "solutions"
version = "0.1.0"
edition = "2021"
description = "bevylings 参考答案（正确代码）"

[dependencies]
bevy = { version = "0.19", optional = true }

[features]
default = []
ch_01 = []
ch_02 = []
ch_03 = []
ch_04 = []
ch_05 = []
ch_06 = []
ch_07 = []
ch_08 = []
ch_09 = []
ch_10 = []
ch_11 = []
ch_12 = []
ch_13 = []
ch_14 = []
ch_15 = []
ch_16 = []
ch_17 = []
ch_18 = []
ch_19 = []
ch_20 = []
ch_21 = []
ch_22 = []
ch_23 = []
ch_24 = []
ch_25 = []
ch_26 = []
ch_27 = []
ch_28 = []
ch_29 = []
ch_30 = []
ch_31 = []
ch_32 = []
ch_33 = []
ch_34 = []
ch_35 = []
sol_0101 = ["ch_01", "dep:bevy"]
sol_0102 = ["ch_01", "dep:bevy"]
sol_0103 = ["ch_01", "dep:bevy"]
sol_0104 = ["ch_01", "dep:bevy"]
sol_0105 = ["ch_01", "dep:bevy"]
sol_0106 = ["ch_01", "dep:bevy"]
sol_0201 = ["ch_02", "dep:bevy"]
sol_0202 = ["ch_02", "dep:bevy"]
sol_0203 = ["ch_02", "dep:bevy"]
sol_0204 = ["ch_02", "dep:bevy"]
sol_0205 = ["ch_02", "dep:bevy"]
sol_0206 = ["ch_02", "dep:bevy"]
sol_0301 = ["ch_03", "dep:bevy"]
sol_0302 = ["ch_03", "dep:bevy"]
sol_0303 = ["ch_03", "dep:bevy"]
sol_0304 = ["ch_03", "dep:bevy"]
sol_0305 = ["ch_03", "dep:bevy"]
sol_0306 = ["ch_03", "dep:bevy"]
sol_0307 = ["ch_03", "dep:bevy"]
sol_0401 = ["ch_04", "dep:bevy"]
sol_0402 = ["ch_04", "dep:bevy"]
sol_0403 = ["ch_04", "dep:bevy"]
sol_0404 = ["ch_04", "dep:bevy"]
sol_0501 = ["ch_05", "dep:bevy"]
sol_0502 = ["ch_05", "dep:bevy"]
sol_0503 = ["ch_05", "dep:bevy"]
sol_0504 = ["ch_05", "dep:bevy"]
sol_0601 = ["ch_06", "dep:bevy"]
sol_0602 = ["ch_06", "dep:bevy"]
sol_0603 = ["ch_06", "dep:bevy"]
sol_0604 = ["ch_06", "dep:bevy"]
sol_0701 = ["ch_07", "dep:bevy"]
sol_0702 = ["ch_07", "dep:bevy"]
sol_0703 = ["ch_07", "dep:bevy"]
sol_0704 = ["ch_07", "dep:bevy"]
sol_0705 = ["ch_07", "dep:bevy"]
sol_0706 = ["ch_07", "dep:bevy"]
sol_0707 = ["ch_07", "dep:bevy"]
sol_0801 = ["ch_08", "dep:bevy"]
sol_0802 = ["ch_08", "dep:bevy"]
sol_0803 = ["ch_08", "dep:bevy"]
sol_0804 = ["ch_08", "dep:bevy"]
sol_0805 = ["ch_08", "dep:bevy"]
sol_0806 = ["ch_08", "dep:bevy"]
sol_0807 = ["ch_08", "dep:bevy"]
sol_0901 = ["ch_09", "dep:bevy"]
sol_0902 = ["ch_09", "dep:bevy"]
sol_0903 = ["ch_09", "dep:bevy"]
sol_0904 = ["ch_09", "dep:bevy"]
sol_1001 = ["ch_10", "dep:bevy"]
sol_1002 = ["ch_10", "dep:bevy"]
sol_1003 = ["ch_10", "dep:bevy"]
sol_1004 = ["ch_10", "dep:bevy"]
sol_1101 = ["ch_11", "dep:bevy"]
sol_1102 = ["ch_11", "dep:bevy"]
sol_1103 = ["ch_11", "dep:bevy"]
sol_1104 = ["ch_11", "dep:bevy"]
sol_1201 = ["ch_12", "dep:bevy"]
sol_1202 = ["ch_12", "dep:bevy"]
sol_1203 = ["ch_12", "dep:bevy"]
sol_1301 = ["ch_13", "dep:bevy"]
sol_1302 = ["ch_13", "dep:bevy"]
sol_1303 = ["ch_13", "dep:bevy"]
sol_1304 = ["ch_13", "dep:bevy"]
sol_1305 = ["ch_13", "dep:bevy"]
sol_1401 = ["ch_14", "dep:bevy"]
sol_1402 = ["ch_14", "dep:bevy"]
sol_1403 = ["ch_14", "dep:bevy"]
sol_1404 = ["ch_14", "dep:bevy"]
sol_1501 = ["ch_15", "dep:bevy"]
sol_1502 = ["ch_15", "dep:bevy"]
sol_1503 = ["ch_15", "dep:bevy"]
sol_1504 = ["ch_15", "dep:bevy"]
sol_1601 = ["ch_16", "dep:bevy"]
sol_1602 = ["ch_16", "dep:bevy"]
sol_1603 = ["ch_16", "dep:bevy"]
sol_1604 = ["ch_16", "dep:bevy"]
sol_1701 = ["ch_17", "dep:bevy"]
sol_1702 = ["ch_17", "dep:bevy"]
sol_1703 = ["ch_17", "dep:bevy"]
sol_1704 = ["ch_17", "dep:bevy"]
sol_1801 = ["ch_18", "dep:bevy"]
sol_1802 = ["ch_18", "dep:bevy"]
sol_1803 = ["ch_18", "dep:bevy"]
sol_1804 = ["ch_18", "dep:bevy"]
sol_1901 = ["ch_19", "dep:bevy"]
sol_1902 = ["ch_19", "dep:bevy"]
sol_1903 = ["ch_19", "dep:bevy"]
sol_1904 = ["ch_19", "dep:bevy"]
sol_2001 = ["ch_20", "dep:bevy"]
sol_2002 = ["ch_20", "dep:bevy"]
sol_2003 = ["ch_20", "dep:bevy"]
sol_2004 = ["ch_20", "dep:bevy"]
sol_2005 = ["ch_20", "dep:bevy"]
sol_2006 = ["ch_20", "dep:bevy"]
sol_2101 = ["ch_21", "dep:bevy"]
sol_2102 = ["ch_21", "dep:bevy"]
sol_2103 = ["ch_21", "dep:bevy"]
sol_2104 = ["ch_21", "dep:bevy"]
sol_2105 = ["ch_21", "dep:bevy"]
sol_2106 = ["ch_21", "dep:bevy"]
sol_2107 = ["ch_21", "dep:bevy"]
sol_2201 = ["ch_22", "dep:bevy"]
sol_2202 = ["ch_22", "dep:bevy"]
sol_2203 = ["ch_22", "dep:bevy"]
sol_2204 = ["ch_22", "dep:bevy"]
sol_2301 = ["ch_23", "dep:bevy"]
sol_2302 = ["ch_23", "dep:bevy"]
sol_2303 = ["ch_23", "dep:bevy"]
sol_2401 = ["ch_24", "dep:bevy"]
sol_2402 = ["ch_24", "dep:bevy"]
sol_2403 = ["ch_24", "dep:bevy"]
sol_2501 = ["ch_25", "dep:bevy"]
sol_2502 = ["ch_25", "dep:bevy"]
sol_2503 = ["ch_25", "dep:bevy"]
sol_2601 = ["ch_26", "dep:bevy"]
sol_2602 = ["ch_26", "dep:bevy"]
sol_2603 = ["ch_26", "dep:bevy"]
sol_2604 = ["ch_26", "dep:bevy"]
sol_2701 = ["ch_27", "dep:bevy"]
sol_2702 = ["ch_27", "dep:bevy"]
sol_2703 = ["ch_27", "dep:bevy"]
sol_2704 = ["ch_27", "dep:bevy"]
sol_2801 = ["ch_28", "dep:bevy"]
sol_2802 = ["ch_28", "dep:bevy"]
sol_2803 = ["ch_28", "dep:bevy"]
sol_2804 = ["ch_28", "dep:bevy"]
sol_2805 = ["ch_28", "dep:bevy"]
sol_2901 = ["ch_29", "dep:bevy"]
sol_2902 = ["ch_29", "dep:bevy"]
sol_2903 = ["ch_29", "dep:bevy"]
sol_2904 = ["ch_29", "dep:bevy"]
sol_3001 = ["ch_30", "dep:bevy"]
sol_3002 = ["ch_30", "dep:bevy"]
sol_3003 = ["ch_30", "dep:bevy"]
sol_3101 = ["ch_31", "dep:bevy"]
sol_3102 = ["ch_31", "dep:bevy"]
sol_3103 = ["ch_31", "dep:bevy"]
sol_3201 = ["ch_32", "dep:bevy"]
sol_3202 = ["ch_32", "dep:bevy"]
sol_3203 = ["ch_32", "dep:bevy"]
sol_3301 = ["ch_33", "dep:bevy"]
sol_3302 = ["ch_33", "dep:bevy"]
sol_3303 = ["ch_33", "dep:bevy"]
sol_3401 = ["ch_34", "dep:bevy"]
sol_3402 = ["ch_34", "dep:bevy"]
sol_3403 = ["ch_34", "dep:bevy"]
sol_3404 = ["ch_34", "dep:bevy"]
sol_3501 = ["ch_35", "dep:bevy"]
sol_3502 = ["ch_35", "dep:bevy"]
sol_3503 = ["ch_35", "dep:bevy"]
